### ISSUE TITLE
[FEAT] Add support for Recently visited Contexts ( i.e. Recent Branches/PRs/Issues)

### ISSUE THREAD

**Issue by Palanikannan1437** [gitpod-samples/Gitpod-Raycast-Extension#11]
# Description
Along with Recently visited repositories, showing Recent CONTEXTS would be helpful for faster access

# Existing Behaviour
<img width="1000" alt="gitpod 2023-01-20 at 17 54 20" src="https://user-images.githubusercontent.com/73993394/213694283-74920bdc-e21c-42ad-a0dd-8cbf3a5967ca.png">

Shows recently visited repositories

# Why?

The current behaviour results in bad DX, incase the user wants to open a particular context repetitively while working on a particular branch!

**Comment by henit-chobisa** [comment]
I think we need to pull this up, this week
I think this is a needy one

**Comment by henit-chobisa** [comment]
@Palanikannan1437, can you shoot this down ? 🔫

**Comment by Palanikannan1437** [comment]
Sure thing!

**Comment by Palanikannan1437** [comment]
done in #25
