### ISSUE TITLE
Request: Integrate with IDE options + Workspace Classes

### ISSUE THREAD

**Issue by loujaybee** [gitpod-samples/Gitpod-Raycast-Extension#17]
Did you know through the URL you can customise the editor, class and some other stuff? 

Would be cool to be able to open a workspace through the raycast extension using these URL options. 

You can see some of them here: https://github.com/gitpod-io/website/pull/3377/files

Have a play, maybe it could be integrated somehow? 😍

**Comment by Palanikannan1437** [comment]
Hey @loujaybee, Ohh wow! This is amazing and a NEEDED ONE!! We certainly were thinking of adding this, thank you so much for pointing us to this 🧡🧡

This'll definitely be present in the next release along with "user preferences" to set a default IDE type within the raycast extension itself 🚀

**Comment by Palanikannan1437** [comment]
@Siddhant-K-code, I tried it with the documentation added in [this](https://github.com/gitpod-io/website/pull/3377/files) PR

1. With showOptions=true 
https://gitpod.io/?showOptions=true&useLatest=true&editor=code-desktop&workspaceClass=g1-large#https://github.com/gitpod-io/website
<img width="621" alt="image" src="https://user-images.githubusercontent.com/73993394/223535977-d36a800c-13f5-426b-b1de-30a16ffe9410.png">

2. With showOptions=false 
https://gitpod.io/?showOptions=false&useLatest=true&editor=code-desktop&workspaceClass=g1-large#https://github.com/gitpod-io/website

<img width="621" alt="image" src="https://user-images.githubusercontent.com/73993394/223534746-7ec696a8-bfe4-4865-9574-2a50901282d5.png">

But as you could see, both show the same results, I effectively do get to this page...instead we would want to directly get to this page....

<img width="621" alt="image" src="https://user-images.githubusercontent.com/73993394/223535256-4610be91-466e-4027-92c6-86655a1ef14d.png">

Is this the intended behaviour for `showOptions` or am I missing out on something here 😅?

**Comment by filiptronicek** [comment]
I really like this suggestion. If the extension could also always remember the options you used[^1], it'd be even more efficient!

[^1]: I imagine this could be implemented as follows: when you open a context, the extension would store the settings used as the default settings for the repository, allowing the user to change it later. When you open another branch with different settings, it would also store it, so that you can have different options even for branches - if the branch config would be the same, it would default to the repository settings and if those are not available, then to the global ones.

**Comment by Palanikannan1437** [comment]
Aha, that's exactly what we're going forward with!! The things you suggested put things into picture in an even better way 🚀

This is what I've come up with after your suggestions and ideas!

1. There'd be a global preference which the user would be asked to choose after login which would be the default preference for all the repositories and their contexts as well

2. There'd be a preference at a repository level, which they can access by say (CMD + "w") or something similar or directly from the actions menu in Raycast

3. There'd be a preference at a context level (for individual branches, repos and issues), which users can access and configure by say (CMD + "w") or something similar or directly from the actions menu in Raycast!

The preferences would cascade as you suggested i.e.
a. If preferences are not set at a context level then preferences set at a repository level will be used

b. If preferences are not set at a repository level then preferences set at the global level will be used
