### ISSUE TITLE
Add option to open GitHub (as well as open a workspace)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-samples/Gitpod-Raycast-Extension#18]
When getting to this page where I can select branches, and issues. I almost found myself wanting to click an issue, to go re-read and re-familiarise with the GitHub issue, or PR, and didn't want to open a workspace straight away. Is there someway we could blend "open in GitHub" and "open a workspace" type actions together? 🤔 

<img width="791" alt="image" src="https://user-images.githubusercontent.com/5528307/218061831-90c5c1ab-2def-407b-9e90-7f6d2a4cb9be.png">

**Comment by Palanikannan1437** [comment]
Hey @loujaybee, thanks so much for using the app and suggestions! 

The action of "Open in GitHub" already exists 🚀, you could simple go to the respective context and press "CMD + Enter" on your keyboard to open the Context (respective PR, Issue or Branch)

**Comment by Palanikannan1437** [comment]
Soon we'll be adding a feature by which you could preview the GitHub Issue/PR's Markdown within the Raycast app itself 👀

**Comment by Palanikannan1437** [comment]
> feature

Being tracked at #20
