### ISSUE TITLE
Add support to disable menubar icon

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-samples/Gitpod-Raycast-Extension#21]
### Problem to solve

The menubar icon is a nice feature, but could push away users from using the extension if it's always visible.

Raycast is also a keyboard-first kind of application which guides users to navigate through keyboard shortcuts, and more.

### Proposal

Introduce an option in the extension settings that disables the menubar icon.

**Comment by henit-chobisa** [comment]
Hey @gtsiolis, thanks for opening the issues, actually raycast gives a option to activate & deactivate the menu-bar command, but that's through raycast preference, 
I will look into it and make sure to find a way we can disable the menu bar icon on User's preference with a faster pace. ✌️

**Comment by henit-chobisa** [comment]
Hey @gtsiolis, I have looked up for this 🖱️
Raycast gives us a shortcut to `Deactivate` the menu bar command, through `CMD` + `SHIFT` + `C`, which is more handy to the customers, than going to Raycast preferences. 🧑‍🚀
<img width="886" alt="image" src="https://user-images.githubusercontent.com/72302948/220035697-e0f2fd54-57f2-4d23-98c1-9b7d79b0a055.png">

**Comment by gtsiolis** [comment]
@henit-chobisa I recently showed how GitLab and GitHub extension are doing this with a menu bar command, which you can also disable. Could we do something similar, as it seems like a best practice? Alternatively, going with the proposal above sounds like a good [MVC](https://www.notion.so/gitpod/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e?pvs=4#0c2e0d6c8a99404b97ccdc206b573d72) step forward.

| GitLab | GitHub |
|-|-|
| <img width="600" alt="raycast-gl" src="https://user-images.githubusercontent.com/120486/220073585-ab634728-995e-4181-9e2c-f41b4ef6adc2.png"> | <img width="600" alt="raycast-gh" src="https://user-images.githubusercontent.com/120486/220073590-b6e05653-686c-45db-8f85-8169b7dc9bd3.png"> |

**Comment by Palanikannan1437** [comment]
> @henit-chobisa I recently showed how GitLab and GitHub extension are doing this with a menu bar command, which you can also disable. Could we do something similar, as it seems like a best practice? Alternatively, going with the proposal above sounds like a good [MVC](https://www.notion.so/gitpod/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e?pvs=4#0c2e0d6c8a99404b97ccdc206b573d72) step forward.
> 
> GitLab	GitHub
> <img alt="raycast-gl" width="600" src="https://user-images.githubusercontent.com/120486/220073585-ab634728-995e-4181-9e2c-f41b4ef6adc2.png">	<img alt="raycast-gh" width="600" src="https://user-images.githubusercontent.com/120486/220073590-b6e05653-686c-45db-8f85-8169b7dc9bd3.png">

Hey @gtsiolis, I didn't get how GitLab or GitHub extensions' menubar commands differ 😅

They work exactly the same for me like our Gitpod extensions' menubar command works...

1. On the first click on the command... we "Activate" the command!

<img width="1000" alt="Raycast 2023-02-20 at 17 54 23" src="https://user-images.githubusercontent.com/73993394/220106692-99105eb3-3af5-4db9-b30c-baa620bb7b34.png">

2. On the subsequent clicks on the command... we "Refresh " the command! 
<img width="1000" alt="Raycast 2023-02-20 at 17 58 30" src="https://user-images.githubusercontent.com/73993394/220108227-9c3333ea-872d-4164-ab51-e39deff6c364.png">

For now the only way to deactivate them seems to be how @henit-chobisa suggested since Raycast has actions on Menubar commands fixed and non configurable

**Comment by gtsiolis** [comment]
> I didn't get how GitLab or GitHub extensions' menubar commands differ

My bad, @henit-chobisa! I didn't see the Menu Bar Command title on the screenshots above in https://github.com/gitpod-samples/Gitpod-Raycast-Extension/issues/21#issuecomment-1436457602.

> They work exactly the same for me like our Gitpod extensions' menubar command works...

You're right! 💯

**Comment by henit-chobisa** [comment]
> > I didn't get how GitLab or GitHub extensions' menubar commands differ
> 
> 
> 
> My bad, @henit-chobisa! I didn't see the Menu Bar Command title on the screenshots above in https://github.com/gitpod-samples/Gitpod-Raycast-Extension/issues/21#issuecomment-1436457602.
> 
> 
> 
> > They work exactly the same for me like our Gitpod extensions' menubar command works...
> 
> 
> 
> You're right! 💯 

Glad that it's resolved @gtsiolis 
Should I close the issue then ?

**Comment by gtsiolis** [comment]
Sounds good, thanks for helping clarify this, @henit-chobisa!
