### ISSUE TITLE
Extension configuration

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-samples/Gitpod-Raycast-Extension#29]
I would like to propose a way to change the configuration of the extension. 

The most important thing I would like to change is Gitpod's endpoint: for Gitpod Dedicated and for some still running self-hosted installations, the host differs. For example https://github.com/gitpod-io/browser-extension allows for change of Gitpod URL.

**Comment by Palanikannan1437** [comment]
Ohh for sure @filiptronicek, missed this edge case! 

Would love to know more such edge cases and configurations that are needed!
