### ISSUE TITLE
[Suggestion] - init a Gitpod file

### ISSUE THREAD

**Issue by jeanphibaconnais** [gitpod-samples/Gitpod-Raycast-Extension#45]
Oh, there is not a .gitpod file. I can work on this to offer a workspace ready to use 😄

**Comment by Palanikannan1437** [comment]
Hey @jeanphibaconnais, thanks so much for this! But I'm not sure how this'd work out as for developing the Raycast App you'd have to clone this locally and simply run `npm i` and `npm run dev`
