### ISSUE TITLE
[Suggestion] - New Workspaces features

### ISSUE THREAD

**Issue by jeanphibaconnais** [gitpod-samples/Gitpod-Raycast-Extension#48]
Hello 👋
I would be interested to see information about workspaces as the list of actives, and why not to be able to remove a workspace 😄

**Comment by Palanikannan1437** [comment]
Hey @jeanphibaconnais, sorry but I didn't get you 😅, could you please explain it again?

Currently we have the `List Gitpod Workspaces` command, which shows three states of the workspaces

1. Active
2. Progressing
3. Inactive

<img width="1000" alt="gitpod 2023-03-29 at 12 59 03" src="https://user-images.githubusercontent.com/73993394/228458821-88f27bb4-9202-4006-a3b5-608a4cd5d00f.png">

And currently we have:

1. Option to start an `Inactive` workspaces
<img width="1000" alt="gitpod 2023-03-29 at 13 03 49" src="https://user-images.githubusercontent.com/73993394/228459928-6847a29a-105e-45cb-a36c-1225e61fae55.png">

2. Option to **stop** an `Active` workspace
3. Option to **open** a `Active` workspace in VSCode and the Browser
<img width="1000" alt="gitpod 2023-03-29 at 13 01 25" src="https://user-images.githubusercontent.com/73993394/228459726-39212e8b-3eaa-41aa-a263-c1950e79dda1.png">

We'll soon add the "delete workspace" feature as well 🧡

**Comment by jeanphibaconnais** [comment]
Oh great ! Thank you for the explanations.

**Comment by Palanikannan1437** [comment]
That's awesome 🧡, please let us know if you face issues/have any queries here or at [discord](https://www.gitpod.io/chat)
